onlineShop.WEB/Models/ErrorViewModel.cs
using System;

namespace onlineShop.WEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

onlineShop.WEB/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onlineShop.WEB.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

onlineShop.WEB/Controllers/DrinkController.cs
using Microsoft.AspNetCore.Mvc;
using onlineShop.WEB.Data.Interfaces;
using onlineShop.WEB.Data.Models;
using onlineShop.WEB.Views.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onlineShop.WEB.Controllers
{
    public class DrinkController : Controller
    {
        private readonly IDrinkRepository drinkRepository;
        private readonly ICategoryRepository categoryRepository;

        public DrinkController(IDrinkRepository drinkRepository, ICategoryRepository categoryRepository)
        {
            this.drinkRepository = drinkRepository;
            this.categoryRepository = categoryRepository;
        }

        public IActionResult List(string category)
        {
            string _category = category;
            IEnumerable<Drink> drinks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                drinks = drinkRepository.Drinks.OrderBy(p => p.DrinkId);
                currentCategory = "All drinks";
            }
            else
            {
                if (string.Equals("Alcoholic", _category, StringComparison.OrdinalIgnoreCase))
                    drinks = drinkRepository.Drinks.Where(p => p.Category.CategoryName.Equals("Alcoholic")).OrderBy(p => p.Name);
                else
                    drinks = drinkRepository.Drinks.Where(p => p.Category.CategoryName.Equals("Non-alcoholic")).OrderBy(p => p.Name);

                currentCategory = _category;
            }

            return View(new DrinkListViewModel
            {
                Drinks = drinks,
                CurrentCategory = currentCategory
            });
        }
    }
}

onlineShop.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using onlineShop.WEB.Views.ViewModels;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using onlineShop.WEB.Views;
using onlineShop.WEB.Data.Interfaces;

namespace onlineShop.WEB.Controllers
{
    public class HomeController : Controller
    {        
        private readonly IDrinkRepository drinkRepository;

        public HomeController(IDrinkRepository drinkRepository)
        {            
            this.drinkRepository = drinkRepository;
        }

        public IActionResult Index()
        {
            var vm = new HomeViewModel
            {
                PreferredDrinks = drinkRepository.PreferredDrinks
            };

            return View(vm);
        }
       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

onlineShop.WEB/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using onlineShop.WEB.Data.Interfaces;
using onlineShop.WEB.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onlineShop.WEB.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly ShoppingCart shoppingCart;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            this.orderRepository = orderRepository;
            this.shoppingCart = shoppingCart;
        }
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]        
        public IActionResult Checkout(Order order)
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.ShoppingCartItems = items;
            if (shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some drinks first");
            }

            if (ModelState.IsValid || !ModelState.IsValid)
            {
                orderRepository.CreateOrder(order);
                shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";
            return View();
        }

    }
}

onlineShop.WEB/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using onlineShop.WEB.Data.Interfaces;
using onlineShop.WEB.Data.Models;
using onlineShop.WEB.Views.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onlineShop.WEB.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IDrinkRepository drinkRepository;
        private readonly ShoppingCart shoppingCart;

        public ShoppingCartController(IDrinkRepository drinkRepository, ShoppingCart shoppingCart)
        {
            this.drinkRepository = drinkRepository;
            this.shoppingCart = shoppingCart;
        }

        public IActionResult Index()
        {
            var items = shoppingCart.GetShoppingCartItems();
            shoppingCart.ShoppingCartItems = items;

            var vm = new ShoppingCartViewModel
            {
                ShoppingCart = this.shoppingCart,
                ShoppingCartTotal = this.shoppingCart.GetShoppingCartTotal()
            };

            return View(vm);
        }

        public RedirectToActionResult AddToShoppingCart(int drinkId)
        {
            var selectedDrink = drinkRepository.Drinks.FirstOrDefault(x => x.DrinkId == drinkId);

            if (selectedDrink != null)
            {
                shoppingCart.AddToCart(selectedDrink, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int drinkId)
        {
            var selectedDrink = drinkRepository.Drinks.FirstOrDefault(x => x.DrinkId == drinkId);

            if (selectedDrink != null)
            {
                shoppingCart.RemoveFromCart(selectedDrink);
            }

            return RedirectToAction("Index");
        }
    }
}

onlineShop.WEB/ViewComponents/DinamicMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using onlineShop.WEB.Data.Interfaces;
using onlineShop.WEB.Views.ViewModels;

namespace onlineShop.WEB.ViewComponents
{
    public class DinamicMenuViewComponent:ViewComponent
    {
        private readonly ICategoryRepository categoryRepository;

        public DinamicMenuViewComponent(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }

        public IViewComponentResult Invoke()
        {
            var categories = categoryRepository.Categories.OrderBy(x=>x.CategoryName);

            var vm = new DinamicMenuViewModel()
            {
                Categories = categories,
            };

            return View(vm);
        }
    }
}

onlineShop.WEB/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using onlineShop.WEB.Data.Models;
using onlineShop.WEB.Views.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onlineShop.WEB.ViewComponents
{    
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly ShoppingCart shoppingCart;

        public ShoppingCartViewComponent(ShoppingCart shoppingCart)
        {
            this.shoppingCart = shoppingCart;
        }

        public IViewComponentResult  Invoke()
        {
            var items = shoppingCart.GetShoppingCartItems(); //new List<ShoppingCartItem> { new ShoppingCartItem(), new ShoppingCartItem() };
            shoppingCart.ShoppingCartItems = items;

            var vm = new ShoppingCartViewModel
            {
                ShoppingCart = shoppingCart,
                ShoppingCartTotal = shoppingCart.GetShoppingCartTotal()
            };

            return View(vm);
        }
    }
}

onlineShop.WEB/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h1>Contact us</h1>
<h2>If you .. .</h2>

<email address="boya@gmail.com" content="Email us"></email>

onlineShop.WEB/Views/Drink/List.cshtml
@model DrinkListViewModel
@{
    ViewData["Title"] = "All Drinks";
}

@foreach (var drink in Model.Drinks)
{
    @Html.Partial("DrinkSummary", drink);
}

onlineShop.WEB/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

@Html.Partial("Carousel")

<h2>Preferred drinks of the week</h2>

<div class="row">
    @foreach (var drink in Model.PreferredDrinks)
    {
       @Html.Partial("DrinkSummary", drink)
    }
</div>

onlineShop.WEB/Views/Order/Checkout.cshtml
@using onlineShop.WEB.Data.Models
@model Order

<div class="row orderForm ">
    <h3 class="text-center">You are just one step away from ordering your drinks.</h3>

    <form asp-controller="Order" asp-action="Checkout" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <label asp-for="LastName" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="AddressLine1" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="AddressLine2" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="AddressLine2" class="form-control" />
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ZipCode" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="btn-group col-md-offset-2 col-md-8">
                <input class="btn btn-success" type="submit" value="Complete order" />
                @*<input class="btn btn-default" type="submit" value="Return " />*@
            </div>
        </div>

    </form>
</div>

onlineShop.WEB/Views/Order/CheckoutComplete.cshtml
<h1>
    @ViewBag.CheckoutCompleteMessage
</h1>

onlineShop.WEB/Views/Shared/Carousel.cshtml
<div id="carousel123" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carousel123" data-slide-to="0" class="active"></li>
        <li data-target="#carousel123" data-slide-to="1"></li>
        <li data-target="#carousel123" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/Images/carousel1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carousel123" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel123" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

onlineShop.WEB/Views/Shared/Components/DinamicMenu/Default.cshtml
@model DinamicMenuViewModel
    <!-- Navigation (Start)-->
<nav class="navbar navbar-expand-md fixed-top">
    <a class="navbar-brand" href="#"><img src="~/Images/logo.png" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"> </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="resourcesDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Drinks</a>

                <div class="dropdown-menu" aria-labelledby="resourcesDropdown">
                    @foreach (var category in Model.Categories)
                    {
                        <a class="nav-link" asp-controller="Drink" asp-action="List" asp-route-category="@category.CategoryName">@category.CategoryName</a>
                    }

                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>

        </ul>
        <form class="navbar-form navbar-right" asp-controller="Drink" asp-action="Search" method="get">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search for a drink" name="searchString" value="@ViewData["searchString"]">
            </div>
        </form>
    </div>
</nav>
<!-- Navigation (End)-->

onlineShop.WEB/Views/Shared/Components/ShoppingCart/Default.cshtml
@model ShoppingCartViewModel

@if (Model.ShoppingCart.ShoppingCartItems.Count > 0)
{ 
    <li>
        <a asp-controller="ShoppingCart">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <span id="cart-status">
                @Model.ShoppingCart.ShoppingCartItems.Count
            </span>
        </a>
    </li>
}

onlineShop.WEB/Views/Shared/DrinkSummary.cshtml
@using onlineShop.WEB.Data.Models;
@model Drink

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a>@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success" 
                   id="cartButton" 
                   asp-controller="ShoppingCart" 
                   asp-action="AddToShoppingCart" 
                   asp-route-drinkId="@Model.DrinkId">
                    Add to cart !!!
                </a>
            </p>
        </div>
    </div>
</div>

onlineShop.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - onlineShop.WEB</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div class="home-inner">

    </div>

    @await Component.InvokeAsync("DinamicMenu")

    @await Component.InvokeAsync("ShoppingCart")

    <div class="container body-content " style="padding:50px;">
        @RenderBody()

        <hr />

        <footer>
            <hr />
           <a target="_blank" href="https://">&copy; 2020 - Boya</a>
        </footer>

    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

onlineShop.WEB/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the drinks in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Drink</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Drink.Name</td>
                    <td class="text-right">@line.Drink.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Drink.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-drinkId="@line.Drink.DrinkId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                @*<a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        Add more drinks<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a asp-controller="Drink" asp-action="List" asp-route-category="Alcoholic">Alcoholic</a></li>
                        <li><a asp-controller="Drink" asp-action="List" asp-route-category="Non-alcoholic">Non Alcoholic</a></li>
                    </ul>*@
            </a>
        </div>
    </div>
</div>